version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:8080
